"WARNING: this file was automatically generated by commented code within mathpad.py"
import sympy.physics.units.definitions.unit_definitions as u
from mathpad.physical_quantities import *

atomic_mass_constant = PhysicalQuantity(
    u.atomic_mass_constant, 1, u.atomic_mass_constant.dimension)
avogadro = PhysicalQuantity(u.avogadro, 1, u.avogadro.dimension)
avogadro_constant = PhysicalQuantity(
    u.avogadro_constant, 1, u.avogadro_constant.dimension)
boltzmann = PhysicalQuantity(u.boltzmann, 1, u.boltzmann.dimension)
boltzmann_constant = PhysicalQuantity(
    u.boltzmann_constant, 1, u.boltzmann_constant.dimension)
coulomb_constant = PhysicalQuantity(
    u.coulomb_constant, 1, u.coulomb_constant.dimension)
coulombs_constant = PhysicalQuantity(
    u.coulombs_constant, 1, u.coulombs_constant.dimension)
electric_constant = PhysicalQuantity(
    u.electric_constant, 1, u.electric_constant.dimension)
electric_force_constant = PhysicalQuantity(
    u.electric_force_constant, 1, u.electric_force_constant.dimension)
faraday_constant = PhysicalQuantity(
    u.faraday_constant, 1, u.faraday_constant.dimension)
gravitational_constant = PhysicalQuantity(
    u.gravitational_constant, 1, u.gravitational_constant.dimension)
josephson_constant = PhysicalQuantity(
    u.josephson_constant, 1, u.josephson_constant.dimension)
magnetic_constant = PhysicalQuantity(
    u.magnetic_constant, 1, u.magnetic_constant.dimension)
molar_gas_constant = PhysicalQuantity(
    u.molar_gas_constant, 1, u.molar_gas_constant.dimension)
stefan = PhysicalQuantity(u.stefan, 1, u.stefan.dimension)
stefan_boltzmann_constant = PhysicalQuantity(
    u.stefan_boltzmann_constant, 1, u.stefan_boltzmann_constant.dimension)
u0 = PhysicalQuantity(u.u0, 1, u.u0.dimension)
vacuum_permeability = PhysicalQuantity(
    u.vacuum_permeability, 1, u.vacuum_permeability.dimension)
von_klitzing_constant = PhysicalQuantity(
    u.von_klitzing_constant, 1, u.von_klitzing_constant.dimension)
