"WARNING: this file was automatically generated by commented code within mathpad.py, and then modified slightly"
import sympy.physics.units.definitions.unit_definitions as u
from mathpad.val import Val

atomic_mass_constant = Val(u.atomic_mass_constant, 1)
avogadro_constant = Val(u.avogadro_constant, 1)
boltzmann_constant = Val(u.boltzmann_constant, 1)
coulomb_constant = Val(u.coulomb_constant, 1)
coulombs_constant = Val(u.coulombs_constant, 1)
electric_constant = Val(u.electric_constant, 1)
electric_force_constant = Val(u.electric_force_constant, 1)
faraday_constant = Val(u.faraday_constant, 1)
gravitational_constant = Val(u.gravitational_constant, 1)
josephson_constant = Val(u.josephson_constant, 1)
magnetic_constant = Val(u.magnetic_constant, 1)
molar_gas_constant = Val(u.molar_gas_constant, 1)
stefan_boltzmann_constant = Val(u.stefan_boltzmann_constant, 1)
von_klitzing_constant = Val(u.von_klitzing_constant, 1)