"WARNING: this file was automatically generated by commented code within mathpad.py, and then modified slightly"
import sympy.physics.units.definitions.unit_definitions as u
from mathpad.val import *
