"WARNING: this file was automatically generated by commented code within mathpad.py, and then modified slightly"
import sympy.physics.units.definitions.unit_definitions as u
from mathpad.val import *

A = Current(u.A)
Bq = Frequency(u.Bq)
C = Charge(u.C)
D = Dioptre(u.D)
F = Capacitance(u.F)
G = GravityConstant(u.G)
Gy = Gray(u.Gy)
H = Inductance(u.H)
Hz = Frequency(u.Hz)
J = Energy(u.J)
K = Temperature(u.K)